name: Deploy to DevElaman

on:
  push:
    branches:
      - main
      - stage
      - DevElaman
    paths:
      - 'force-app/**'

jobs:
  deploy:
    deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod'  github.ref == 'refs/heads/stage' && 'stage'  github.ref == 'refs/heads/DevElaman' && 'DevElaman' }}

    steps:

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Install sfdx-git-delta
        run: |
          echo Y | sf plugins install sfdx-git-delta
          sf plugins

      - name: Fetch all branches
        run: git fetch --all

      - name: Create delta packages
        run: |
          mkdir -p changed-sources
          sf sgd source delta \
            --from origin/main \
            --to HEAD \
            --output changed-sources/ \
            --generate-delta \
            --source force-app/main/default

      - name: Authenticate with JWT
        run: |
          echo "${{ secrets.JWT_SERVER_KEY_DEVELAMAN }}" > server.key
          sf org login jwt \
            --username "${{ secrets.DEPLOYMENT_USER_NAME_DEVELAMAN }}" \
            --jwt-key-file server.key \
            --client-id "${{ secrets.CONSUMER_KEY_DEVELAMAN }}" \
            --instance-url "${{ vars.INSTANCE_URL_DEVELAMAN }}" \
            --set-default

      - name: Deploy to org
        run: |
          if [ ! -d "changed-sources/force-app" ] || [ -z "$(ls -A changed-sources/force-app 2>/dev/null)" ]; then
            echo "No metadata changes detected. Skipping deploy."
            exit 0
          fi

          if [ "${{ github.ref }}" == "refs/heads/DevElaman" ]; then
            echo "Deploying to DevElaman org without tests"
            sf project deploy start \
              --source-dir changed-sources/force-app \
              --test-level NoTestRun \
              --wait 60
          else
            echo "Deploying with tests"
            sf project deploy start \
